require("config.options")
require("config.kitty").setup()
require("config.plugins").setup()
require("integrations").setup()
require("config.keymaps")
require("config.autocmds")
require("vscode.workbench").setup()
require("vscode.sidebar").setup()
