-- VS Code muscle memory for the standalone configuration. Space-leader
-- mappings remain available when a terminal cannot encode Ctrl+Shift.
local map = vim.keymap.set
local silent = { silent = true }
local sidebar = function()
  return require("vscode.sidebar")
end

local function save()
  if vim.bo.buftype == "" then
    vim.cmd.update()
  end
end

local function goto_line()
  vim.ui.input({ prompt = "Go to line: " }, function(value)
    local line = tonumber(value)
    if line then
      vim.api.nvim_win_set_cursor(0, { math.min(line, vim.api.nvim_buf_line_count(0)), 0 })
    end
  end)
end

local function save_as()
  vim.ui.input({ prompt = "Save as: ", default = vim.fn.expand("%:p") }, function(path)
    if path and path ~= "" then
      vim.cmd.saveas({ args = { path } })
    end
  end)
end

-- File and editor management
map({ "n", "i", "x" }, "<C-s>", save, { desc = "File: Save", silent = true })
map({ "n", "i", "x" }, "<C-S-s>", save_as, { desc = "File: Save As", silent = true })
map("n", "<C-n>", "<cmd>enew<cr>", { desc = "File: New", silent = true })
map("n", "<C-o>", function()
  Snacks.picker.files()
end, { desc = "File: Open", silent = true })
map("n", "<C-w>", function()
  Snacks.bufdelete()
end, { desc = "Editor: Close", silent = true })
map("n", "<C-S-w>", "<cmd>confirm qall<cr>", { desc = "Window: Close", silent = true })
map("n", "<C-S-t>", function()
  Snacks.picker.recent()
end, { desc = "Editor: Reopen Closed", silent = true })
map("n", "<C-Tab>", "<cmd>bnext<cr>", { desc = "Next Editor", silent = true })
map("n", "<C-S-Tab>", "<cmd>bprevious<cr>", { desc = "Previous Editor", silent = true })
map("n", "<C-PageDown>", "<cmd>bnext<cr>", silent)
map("n", "<C-PageUp>", "<cmd>bprevious<cr>", silent)
map("n", "<A-Left>", "<cmd>pop<cr>", { desc = "Go Back", silent = true })
map("n", "<A-Right>", "<cmd>normal! <C-i><cr>", { desc = "Go Forward", silent = true })

for i = 1, 9 do
  map("n", "<C-" .. i .. ">", "<cmd>BufferLineGoToBuffer " .. i .. "<cr>", {
    desc = "Open Editor " .. i,
    silent = true,
  })
end

-- Workbench and side/panel surfaces
map("n", "<C-p>", function()
  Snacks.picker.files()
end, { desc = "Quick Open", silent = true })
map("n", "<C-S-p>", function()
  Snacks.picker.commands()
end, { desc = "Command Palette", silent = true })
map("n", "<F1>", function()
  Snacks.picker.commands()
end, { desc = "Command Palette", silent = true })
map("n", "<C-b>", function()
  sidebar().toggle_panel()
end, { desc = "View: Toggle Primary Side Bar", silent = true })
map("n", "<C-S-e>", function()
  sidebar().open_explorer()
end, { desc = "View: Explorer", silent = true })
map("n", "<C-S-f>", function()
  sidebar().open_search()
end, { desc = "Search: Find in Files", silent = true })
map("n", "<C-S-g>", function()
  sidebar().open_source_control()
end, { desc = "View: Source Control", silent = true })
map("n", "<C-S-m>", "<cmd>Trouble diagnostics toggle<cr>", { desc = "View: Problems", silent = true })
map("n", "<C-S-x>", function()
  sidebar().open_extensions()
end, { desc = "View: Extensions", silent = true })
map({ "n", "t" }, "<C-`>", function()
  Snacks.terminal.toggle()
end, { desc = "View: Toggle Terminal", silent = true })
map({ "n", "t" }, "<C-j>", function()
  Snacks.terminal.toggle()
end, { desc = "View: Toggle Panel", silent = true })
map("t", "<C-w>", [[<C-\><C-n><cmd>close<cr>]], { desc = "Terminal: Close", silent = true })
map("t", "<Esc><Esc>", [[<C-\><C-n>]], { desc = "Terminal: Focus Editor", silent = true })

-- Search and navigation
map({ "n", "x" }, "<C-f>", "/", { desc = "Find", silent = false })
map("i", "<C-f>", "<Esc>/", { desc = "Find", silent = false })
map("n", "<C-h>", function()
  require("grug-far").open({ prefills = { paths = vim.fn.expand("%") } })
end, { desc = "Replace", silent = true })
map("n", "<C-S-h>", function()
  require("grug-far").open()
end, { desc = "Replace in Files", silent = true })
map("n", "<C-g>", goto_line, { desc = "Go to Line", silent = true })
map("n", "<C-S-o>", function()
  Snacks.picker.lsp_symbols()
end, { desc = "Go to Symbol in Editor", silent = true })
map("n", "<C-t>", function()
  Snacks.picker.lsp_workspace_symbols()
end, { desc = "Go to Symbol in Workspace", silent = true })
map("n", "<F12>", vim.lsp.buf.definition, { desc = "Go to Definition", silent = true })
map("n", "<S-F12>", vim.lsp.buf.references, { desc = "Go to References", silent = true })
map("n", "<F2>", vim.lsp.buf.rename, { desc = "Rename Symbol", silent = true })
map({ "n", "x" }, "<C-.>", vim.lsp.buf.code_action, { desc = "Quick Fix", silent = true })
map("n", "<F8>", function()
  vim.diagnostic.jump({ count = 1, float = true })
end, { desc = "Next Problem", silent = true })
map("n", "<S-F8>", function()
  vim.diagnostic.jump({ count = -1, float = true })
end, { desc = "Previous Problem", silent = true })

-- Familiar text editing
map("n", "<C-a>", "ggVG", { desc = "Select All", silent = true })
map("i", "<C-a>", "<Esc>ggVG", { desc = "Select All", silent = true })
map("n", "<C-c>", '"+yy', { desc = "Copy Line", silent = true })
map("x", "<C-c>", '"+y', { desc = "Copy", silent = true })
map("n", "<C-x>", '"+dd', { desc = "Cut Line", silent = true })
map("x", "<C-x>", '"+d', { desc = "Cut", silent = true })
map("n", "<C-v>", '"+p', { desc = "Paste", silent = true })
map("i", "<C-v>", "<C-r>+", { desc = "Paste", silent = true })
map("x", "<C-v>", '"+p', { desc = "Paste", silent = true })
map("n", "<C-z>", "u", { desc = "Undo", silent = true })
map("i", "<C-z>", "<C-o>u", { desc = "Undo", silent = true })
map("n", "<C-y>", "<C-r>", { desc = "Redo", silent = true })
map("i", "<C-y>", "<C-o><C-r>", { desc = "Redo", silent = true })
map("i", "<C-BS>", "<C-w>", { desc = "Delete Word Left", silent = true })

map("n", "<A-Down>", ":move .+1<cr>==", { desc = "Move Line Down", silent = true })
map("n", "<A-Up>", ":move .-2<cr>==", { desc = "Move Line Up", silent = true })
map("x", "<A-Down>", ":move '>+1<cr>gv=gv", { desc = "Move Selection Down", silent = true })
map("x", "<A-Up>", ":move '<-2<cr>gv=gv", { desc = "Move Selection Up", silent = true })
map("n", "<A-S-Down>", "yyp", { desc = "Copy Line Down", silent = true })
map("n", "<A-S-Up>", "yyP", { desc = "Copy Line Up", silent = true })
map("x", "<A-S-Down>", "y'>pgv", { desc = "Copy Selection Down", silent = true })
map("x", "<A-S-Up>", "y'<Pgv", { desc = "Copy Selection Up", silent = true })
map("n", "<C-CR>", "o<Esc>", { desc = "Insert Line Below", silent = true })
map("i", "<C-CR>", "<Esc>o", { desc = "Insert Line Below", silent = true })
map("n", "<C-S-CR>", "O<Esc>", { desc = "Insert Line Above", silent = true })
map("i", "<C-S-CR>", "<Esc>O", { desc = "Insert Line Above", silent = true })
map("n", "<A-z>", "<cmd>set wrap!<cr>", { desc = "View: Toggle Word Wrap", silent = true })
map("n", "<C-l>", "V", { desc = "Selection: Select Current Line", silent = true })
map("n", "<C-S-k>", '"_dd', { desc = "Editor: Delete Line", silent = true })
map("x", "<C-S-k>", '"_d', { desc = "Editor: Delete Selected Lines", silent = true })
map({ "n", "x" }, "<S-A-f>", function()
  require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "Format Document", silent = true })
map("n", "<C-S-[>", "zc", { desc = "Fold", silent = true })
map("n", "<C-S-]>", "zo", { desc = "Unfold", silent = true })
map({ "n", "i" }, "<C-S-Space>", vim.lsp.buf.signature_help, { desc = "Trigger Parameter Hints", silent = true })

-- Kitty's keyboard protocol makes these shifted navigation keys unambiguous.
map("n", "<S-Left>", "v<Left>", { desc = "Selection: Left", silent = true })
map("n", "<S-Right>", "v<Right>", { desc = "Selection: Right", silent = true })
map("n", "<S-Up>", "v<Up>", { desc = "Selection: Up", silent = true })
map("n", "<S-Down>", "v<Down>", { desc = "Selection: Down", silent = true })
map("n", "<C-S-Left>", "vb", { desc = "Selection: Word Left", silent = true })
map("n", "<C-S-Right>", "ve", { desc = "Selection: Word Right", silent = true })

-- Ctrl+/ is encoded as Ctrl+_ by most terminals.
map("n", "<C-_>", "gcc", { desc = "Toggle Line Comment", remap = true, silent = true })
map("x", "<C-_>", "gc", { desc = "Toggle Comment", remap = true, silent = true })
map("n", "<C-/>", "gcc", { desc = "Toggle Line Comment", remap = true, silent = true })
map("x", "<C-/>", "gc", { desc = "Toggle Comment", remap = true, silent = true })

-- VS Code-style chords
map("n", "<C-k><C-s>", function()
  Snacks.picker.keymaps()
end, { desc = "Preferences: Keyboard Shortcuts", silent = true })
map("n", "<C-k>z", function()
  Snacks.zen()
end, { desc = "View: Zen Mode", silent = true })
map("n", "<C-k>s", "<cmd>wall<cr>", { desc = "File: Save All", silent = true })
map("n", "<C-k><C-w>", function()
  Snacks.bufdelete.all()
end, { desc = "Editors: Close All", silent = true })
map("n", "<C-k>w", function()
  Snacks.bufdelete.other()
end, { desc = "Editors: Close Other Editors", silent = true })
map("n", "<C-k><C-0>", "zM", { desc = "Fold All", silent = true })
map("n", "<C-k><C-j>", "zR", { desc = "Unfold All", silent = true })
map({ "n", "x" }, "<C-k>f", function()
  require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "Format Document", silent = true })
map("n", "<C-,>", function()
  require("vscode.workbench").settings()
end, { desc = "Preferences: Open Settings", silent = true })

-- Discoverable fallbacks and plugin-spec compatibility mappings.
map("n", "<leader><space>", function()
  Snacks.picker.files()
end, { desc = "Quick Open", silent = true })
map("n", "<leader>e", function()
  sidebar().open_explorer()
end, { desc = "Explorer", silent = true })
map("n", "<leader>/", function()
  sidebar().open_search()
end, { desc = "Find in Files", silent = true })
map("n", "<leader>,", function()
  Snacks.picker.buffers()
end, { desc = "Open Editors", silent = true })
map("n", "<leader>st", function()
  require("vscode.workbench").themes()
end, { desc = "Color Theme", silent = true })
map("n", "<leader>sx", function()
  require("vscode.workbench").extensions()
end, { desc = "Extensions", silent = true })
map("n", "<leader>sp", function()
  require("vscode.workbench").settings()
end, { desc = "Settings", silent = true })
map("n", "<leader>qq", "<cmd>confirm qall<cr>", { desc = "Quit", silent = true })
